### ISSUE TITLE
Fix Update/Delete Usage of Firewall Association

### ISSUE THREAD

**Issue by luthermonson** [linode/linode-cloud-controller-manager#146]
The APIs do not currently exist to update or delete a firewall from a nodebalancer. When things like [TPT-2535](https://jira.linode.com/browse/TPT-2535) are completed we can update the logic in CCM to catch annotation changes and update/delete the firewall association.

**Comment by luthermonson** [comment]
@rammanoj

**Comment by rammanoj** [comment]
With the merge of https://github.com/linode/linode_api4-python/pull/356, the feature has been implemented. But I guess this might need to wait till the latest release of linodego or GitHub SHA till the PR could be used. @luthermonson suggestions?
