### ISSUE TITLE
Replacing Terraform to Linode CAPI provider

### ISSUE THREAD

**Issue by mhmxs** [linode/linode-cloud-controller-manager#165]
## General:

* [X] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [X] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [X] Have you explained your rationale for why this feature is needed? 
* [X] Have you offered a proposed implementation/solution? 

----

## Bug Reporting

Linode Terraform provider would be deprecated if not already has been. Would be nice to replace it to an uptodate solution. [Linode CAPI](https://github.com/linode/cluster-api-provider-linode) provider would be a good choice. For more information, please follow the corresponding discussion here: https://github.com/linode/cluster-api-provider-linode/issues/6

### Expected Behavior

Replace cluser management scripts with Kubernetes Golang client calls: https://github.com/linode/linode-cloud-controller-manager/blob/557227247545a824827570c6e511e104f5876e25/e2e/test/framework/cluster.go#L4

- Start CAPI provider with it's dependencies.
- Execute tests
- Tear down test environment
- Upload logs to github

Regarding to CAPI provisioning I think speed is the main factor, because we would like to test project on CI. I think a full featured Kubernetes environment is a bit overkill for this task. So my suggestion is to spinning up a lightweight [Kcp](https://github.com/kcp-dev/kcp) control plane and the capi provider(s) via Docker compose. Plain, old, boring but fast!

----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

**Comment by rahulait** [comment]
We did the changes in https://github.com/linode/linode-cloud-controller-manager/pull/248. Marking this as done.
