### ISSUE TITLE
Error: unknown flag: --port for the ccm-linode pod

### ISSUE THREAD

**Issue by johnlai2004** [linode/linode-cloud-controller-manager#250]
## General:

* [yes ] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [ yes] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

----

## Bug Reporting
Hello, I am following your guide on https://www.linode.com/docs/guides/install-the-linode-ccm-on-unmanaged-kubernetes/

However the ccm-linode pod crashes immediately, and the kubectl logs show this:

```
Linode Cloud Controller Manager starting up
SENTRY_DSN not set, not initializing Sentry
Error: unknown flag: --port
Usage:
  cloud-controller-manager [flags]

Debugging flags:

      --contention-profiling   Enable block profiling, if profiling is enabled
      --profil etc.. etc...
```

I have uploaded a 3 minute video to youtube https://www.youtube.com/watch?v=IEDBK9jYnzQ that shows every step I followed.  In short, I did this:
1. Create a new 4GB linode in Toronto CA
2. hostnamectl set-hostname kube1
3. Run the `install-k8.txt` which is derived from the guides provided by linode (replace the IP address on line 6)
4. Run the `install-ccm.text` which is derived from the guide mentioned at the top of this post (replace the linode api token with your token)

Let me know if I did something wrong, or what I should do next to deploy the CCM in an unmanaged kubernetes infrastructure
### Environment Specifications
Ubuntu 22.04 - ca-central (toronto canada)
----
[install-ccm.txt](https://github.com/user-attachments/files/17970240/install-ccm.txt)
[install-k8.txt](https://github.com/user-attachments/files/17970241/install-k8.txt)

**Comment by rahulait** [comment]
Thanks for reporting it, we'll have a look. Its possible the script has not been updated from long time as its not used much and is outdated. Can you try the helm install which should work just fine from the readme? Or you can manually modify the generated yaml file to match with the flags in latest readme. https://github.com/linode/linode-cloud-controller-manager?tab=readme-ov-file#to-deploy-ccm-linode-run-the-following-command

**Comment by rahulait** [comment]
This is now fixed in latest main branch.
